applications:
- api_domain: api.example.com
  application_name: zap
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: http://www.google.com
  type: api
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
