applications:
- api_domain: api.localhost.com
  application_name: Zap
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://localhost.com
  type: api
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks: []
